# Site settings
title: Parallel Cascades
intro: "Creating Games"
email: emil.a.tonev@gmail.com
url: https://parallel-cascades.github.io
description: "Unity video game development, shader programming and more, using the latest technologies."
keywords: "game, development, software, graphics, shader, shader, Unity, asset, ecs, programming"
meta_author: Emil Tonev

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff7b00 #2dffee 
  primary-rgb: "225, 123, 0"
  navbar: 202020
  secondary:  ffffff
  background: 101010

# Footer settings
footer:
  social: Around the Web

# Social networks usernames
social:
  - title: github
    url: http://github.com/parallel-cascades
  - title: youtube
    url: https://www.youtube.com/channel/UCKGnHCi46kx8paafFJvj3Lg
  - title: unity
    url: https://assetstore.unity.com/publishers/103935?preview=1

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  assets:
    output: true
