# Site settings
title: Parallel Games
email: emil.a.tonev@gmail.com
url: https://tirolinko.github.io
description: "Game development, graphics programming and performant code."
keywords: "game, development, software, graphics, shader, shader, Unity, asset, ecs, programming"
meta_author: Emil Tonev

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f0f0f0 #2dffee 
  primary-rgb: "240, 240, 240"
  secondary:  010101 #ff7300
  accent: FF878B
  background: 101010

# Footer settings
footer:
  social: Around the Web

# Social networks usernames
social:
  - title: github
    url: http://github.com/tirolinko
  - title: youtube
    url: https://www.youtube.com/channel/UCPACWUp6SQD3ASM2EEYFT9Q

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
