# Site settings
title: Parallel Dev
email: emil.a.tonev@gmail.com
url: https://tirolinko.github.io
description: "Game development, graphics programming and performant code."
keywords: "game, development, software, graphics, shader, shader, Unity, asset, ecs, programming"
meta_author: Emil Tonev

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff7b00 #2dffee 
  primary-rgb: "225, 123, 0"
  secondary:  ffffff
  background: 101010

# Footer settings
footer:
  social: Around the Web

# Social networks usernames
social:
  - title: github
    url: http://github.com/tirolinko
  - title: youtube
    url: https://www.youtube.com/channel/UCPACWUp6SQD3ASM2EEYFT9Q

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
