# Site settings
title: Parallel Cascades
intro: "Crafting Video Games and Sharing Creativity"
email: parallelcascades@gmail.com
url: parallelcascades.com
description: "Unity video game development, Unity assets, 3D dynamic shaders, procedural generation, Unity DOTS and ECS."
keywords: "Unity, game development, Unity assets, 3D shaders, dynamic shaders, procedural generation, Unity DOTS, ECS, game programming, space scenes, stars, suns, gas giants, Unity tools, shader programming"
meta_author: Emil Tonev

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5e17eb #ff7b00 #2dffee 
  primary-rgb: "94, 23, 235"
  navbar: 202020
  secondary:  ffffff
  background: 101010

# Footer settings
footer:
  social: Around the Web

# Social networks usernames
social:
  - title: github
    url: http://github.com/parallel-cascades
  - title: youtube
    url: https://www.youtube.com/channel/UCKGnHCi46kx8paafFJvj3Lg
  - title: unity
    url: https://assetstore.unity.com/publishers/103935?preview=1

# Build settings
markdown: kramdown
permalink: pretty

collections:
  assets:
    output: true
  indev:
    output: true
